version: "3"
name: "enitools"
services:
  frontend:
    image: vesso/enitools-fe:latest
    hostname: 'frontend'
    container_name: 'frontend'
    ports:
      - 4200:80
  backend:
    image: vesso/enitools-be:latest
    hostname: 'backend'
    container_name: 'backend'
    ports:
      - 5000:80
    # it overwrites files
    # volumes:
    #   - ./data/:/app/data