name: Build and Publish Frontend

on:
  push:
    branches:
      - master
    tags:
      - fe-v*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: 'Enitools-fe'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract version from package.json
      uses: sergeysova/jq-action@v2
      id: version
      with:
        cmd: 'jq .version ./Enitools-fe/package.json -r'
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./Enitools-fe
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/enitools-fe:latest,${{ secrets.DOCKER_USERNAME }}/enitools-fe:${{ steps.version.outputs.value }}
